# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Gazettes South Africa
email: info@code4sa.org
baseurl: /opengazettes
description: Making South African Government Gazettes freely available.
twitter:
  username: code4sa
logo: /img/logo.png

gems:
  - jekyll-seo-tag

collections:
  gazettes:
    output: true

# Build settings
markdown: kramdown
